### ISSUE TITLE
Migrations didn't run

### ISSUE THREAD

**Issue by davist11** [lukeyouell/craft3-geocookie#12]
I just upgrade to version 1.3.2 and it looks like these migrations didn't run:

* m180815_135218_logs.php
* m180815_140522_logColType.php

**Comment by davist11** [comment]
Looks like the schema version in my DB is `2.2.0`

**Comment by lukeyouell** [comment]
That's strange, I see no reason why the schema version would be set to that value.

Have you tried reverting to the previous version, ensuring that the correct schema version is set before updating?

**Comment by davist11** [comment]
I had not yet, but the version we have on staging is at version 1.2.1 and the schema is set at 2.2.0

**Comment by lukeyouell** [comment]
I'm not sure what to suggest as the plugin's schema version has never been 2.2.0

I think the best course of action is to revert back to a previous version, making sure the schema version is correct and then attempting the update.

Let me know how you get on!

**Comment by davist11** [comment]
Ok, so I bumped the plugin version number back down and set the schema column to `NULL`, and the migrations ran successfully. But now if I visit `/admin/utilities/geo-cookie`, I get the following error:

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'geocookie_log.id' in 'field list' in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `geocook...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /Users/tdavis/sites/hamilton/vendor/lukeyouell/craft-geocookie/src/services/LogService.php(33): craft\db\Query->all()
#6 /Users/tdavis/sites/hamilton/vendor/lukeyouell/craft-geocookie/src/utilities/Log.php(67): lukeyouell\geocookie\services\LogService->getLogs()
#7 /Users/tdavis/sites/hamilton/vendor/lukeyouell/craft-geocookie/src/utilities/Log.php(60): lukeyouell\geocookie\utilities\Log::getLogs()
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/UtilitiesController.php(90): lukeyouell\geocookie\utilities\Log::contentHtml()
#9 [internal function]: craft\controllers\UtilitiesController->actionShowUtility('geo-cookie')
#10 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('show-utility', Array)
#13 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('show-utility', Array)
#14 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('utilities/show-...', Array)
#15 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('utilities/show-...', Array)
#16 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/tdavis/sites/hamilton/public/index.php(46): yii\base\Application->run()
#19 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'geocookie_log.id' in 'field list'
The SQL being executed was: SELECT `geocookie_log`.`id`, `geocookie_log`.`dateCreated`, `geocookie_log`.`status`, `geocookie_log`.`source`, `geocookie_log`.`data`
FROM `craft_geocookie_log`
ORDER BY `dateCreated` DESC in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `geocook...')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `geocook...')
#2 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /Users/tdavis/sites/hamilton/vendor/lukeyouell/craft-geocookie/src/services/LogService.php(33): craft\db\Query->all()
#6 /Users/tdavis/sites/hamilton/vendor/lukeyouell/craft-geocookie/src/utilities/Log.php(67): lukeyouell\geocookie\services\LogService->getLogs()
#7 /Users/tdavis/sites/hamilton/vendor/lukeyouell/craft-geocookie/src/utilities/Log.php(60): lukeyouell\geocookie\utilities\Log::getLogs()
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/controllers/UtilitiesController.php(90): lukeyouell\geocookie\utilities\Log::contentHtml()
#9 [internal function]: craft\controllers\UtilitiesController->actionShowUtility('geo-cookie')
#10 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('show-utility', Array)
#13 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('show-utility', Array)
#14 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('utilities/show-...', Array)
#15 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('utilities/show-...', Array)
#16 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/tdavis/sites/hamilton/public/index.php(46): yii\base\Application->run()
#19 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'geocookie_log.id' in 'field list'
)
```

There are currently no logs in the `geocookie_log` table.

**Comment by lukeyouell** [comment]
Please can you confirm the structure of your `geocookie_log` table?

**Comment by davist11** [comment]
<img width="1123" alt="screen shot 2018-09-12 at 10 52 31 am" src="https://user-images.githubusercontent.com/199985/45433372-ff943080-b679-11e8-8c7d-7a042581a745.png">

**Comment by lukeyouell** [comment]
Are your Craft tables prefixed?

**Comment by davist11** [comment]
Yup, they sure are with `craft` (this was an upgrade from 2->3)

**Comment by lukeyouell** [comment]
From your stack trace that looks to be the issue, I'll see if I can replicate.

**Comment by lukeyouell** [comment]
Fixed in the latest release!

**Comment by davist11** [comment]
Confirmed, no more error. Thanks!
