### ISSUE TITLE
Plugin fails when working locally

### ISSUE THREAD

**Issue by RedKohii** [lukeyouell/craft3-geocookie#3]
The plugin works great! But when working locally i get the following error

```
Neither the property "country" nor one of the methods "country()", "getcountry()"/"iscountry()"/"hascountry()" or "__call()" exist and have public access in class "stdClass".
```

full stack trace here

```
Twig_Error_Runtime: Neither the property "country" nor one of the methods "country()", "getcountry()"/"iscountry()"/"hascountry()" or "__call()" exist and have public access in class "stdClass". in /Users/design5/Documents/Websites/telarc/templates/_structure/_site.html:65
Stack trace:
#0 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(stdClass), 'country', Array, 'any', false, false)
#1 /Users/design5/Documents/Websites/telarc/storage/runtime/compiled_templates/79/79ca6133bc3596c9e821bc5bfe5bdb0ad6a5c722004c15ce05d2743815eb07a6.php(100): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(stdClass), 'country', Array)
#2 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_f94a4377a8b34adfe4d749baf923c73317a551491ca863f14e78b34978f553f0->block_body(Array, Array)
#3 /Users/design5/Documents/Websites/telarc/storage/runtime/compiled_templates/41/416fbd7f9011d33c0f7ed2151c9d92c1b6184eca65467556117182805169c4df.php(189): Twig_Template->displayBlock('body', Array, Array)
#4 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_b27d31bed5938ee2a9579ae09454ec63fb71fac2144b45bd7e20e2d9b934ab04->doDisplay(Array, Array)
#5 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#6 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#8 /Users/design5/Documents/Websites/telarc/storage/runtime/compiled_templates/79/79ca6133bc3596c9e821bc5bfe5bdb0ad6a5c722004c15ce05d2743815eb07a6.php(29): craft\web\twig\Template->display(Array, Array)
#9 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_f94a4377a8b34adfe4d749baf923c73317a551491ca863f14e78b34978f553f0->doDisplay(Array, Array)
#10 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#13 /Users/design5/Documents/Websites/telarc/storage/runtime/compiled_templates/70/7027c84fe1d306f7f67c040c1632cceb1ac7f0cf8f8d6143e926a2488ca474c9.php(28): craft\web\twig\Template->display(Array, Array)
#14 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_4cdb4a815d96e1c196a6d23cb266ccfe8e7346e0289bc5937baaf9618fd25dbc->doDisplay(Array, Array)
#15 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#16 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#18 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#19 /Users/design5/Documents/Websites/telarc/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#20 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('', Array)
#21 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('', Array)
#22 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/Controller.php(128): craft\web\View->renderPageTemplate('', Array)
#23 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('', Array)
#24 [internal function]: craft\controllers\TemplatesController->actionRender('', Array)
#25 /Users/design5/Documents/Websites/telarc/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /Users/design5/Documents/Websites/telarc/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#27 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('render', Array)
#28 /Users/design5/Documents/Websites/telarc/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#29 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#30 /Users/design5/Documents/Websites/telarc/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#31 /Users/design5/Documents/Websites/telarc/vendor/craftcms/cms/src/web/Application.php(263): yii\web\Application->handleRequest(Object(craft\web\Request))
#32 /Users/design5/Documents/Websites/telarc/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#33 /Users/design5/Documents/Websites/telarc/public_html/index.php(22): yii\base\Application->run()
#34 {main}
```

**Comment by lukeyouell** [comment]
@RedKohii can you try dumping the response as [outlined here](https://github.com/lukeyouell/craft-geocookie#debugging) and let me know what you see?

**Comment by RedKohii** [comment]
Sure

```
{
    "ip": "::0",
    "reserved": true,
    "cached": true
}
```

It works perfectly on a test server, just locally , so I'm not sure what's causing the issue

**Comment by lukeyouell** [comment]
Please can you also clear your cookies before doing so, that'll force a new request.

**Comment by RedKohii** [comment]
Pretty much the same

```
{
    "ip": "::0",
    "reserved": true,
    "cached": false
}
```

**Comment by lukeyouell** [comment]
Thanks! I'll look into it tomorrow.

**Comment by RedKohii** [comment]
Thanks :D

**Comment by lukeyouell** [comment]
@RedKohii unfortunately there's very little that can be done about this as the plugin works with the value provided by `Craft::$app->request->getUserIP()`

So the issue isn't related to the plugin. Sorry!
